apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: virtool-job-create-sample
spec:
  jobTargetRef:
    backoffLimit: 1
    completions: 1
    parallelism: 1
    ttlSecondsAfterFinished: 300
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        labels:
          app: jobs-create-sample
      spec:
        containers:
          - name: job-create-sample
            image: virtool/create-sample:4.0.0
            imagePullPolicy: Always
            command: [run-workflow]
            envFrom:
              - configMapRef:
                  name: virtool-jobs-config
            env:
              - name: VT_PROC
                value: "2"
              - name: VT_MEM
                value: "4"
              - name: VT_REDIS_LIST_NAME
                value: "jobs_create_sample"
            resources:
              limits:
                cpu: "3"
                memory: 5Gi
                ephemeral-storage: 25G
              requests:
                cpu: "3"
                memory: 5Gi
                ephemeral-storage: 25G
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 1
  triggers:
    - type: redis
      metadata:
        addressFromEnv: VT_REDIS_HOST
        passwordFromEnv: VT_REDIS_PASSWORD
        listName: jobs_create_sample
        listLength: "1"
