apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: virtool-job-create-subtraction
spec:
  jobTargetRef:
    backoffLimit: 1
    completions: 1
    parallelism: 1
    ttlSecondsAfterFinished: 300
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        labels:
          app: jobs-create-subtraction
      spec:
        containers:
          - name: job-create-subtraction
            image: ghcr.io/virtool/create-subtraction:5.1.2
            imagePullPolicy: Always
            command: [run-workflow]
            envFrom:
              - configMapRef:
                  name: virtool-jobs-config
            env:
              - name: VT_PROC
                value: "2"
              - name: VT_MEM
                value: "2"
              - name: VT_REDIS_LIST_NAME
                value: "jobs_create_subtraction"
            resources:
              limits:
                cpu: "3"
                memory: 10Gi
              requests:
                cpu: "3"
                memory: 10Gi
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 1
  triggers:
    - type: redis
      metadata:
        addressFromEnv: VT_REDIS_HOST
        passwordFromEnv: VT_REDIS_PASSWORD
        listName: jobs_create_subtraction
        listLength: "1"
