images:
  - name: ghcr.io/virtool/ui
    newTag: 7.5.2

labels:
  - pairs:
      app: virtool-ui
    includeSelectors: true
    includeTemplates: true

namePrefix: virtool-

resources:
  - deployment.yaml
  - service.yaml