tasks:
  - fileName: "add-subtraction-files"
    taskName: "add_subtraction_files"
    kubeName: "virtool-task-add-subtraction-files"
    schedule: "*/10 * * * *"
  - fileName: "ensure-index-files"
    taskName: "ensure_index_files"
    kubeName: "virtool-task-ensure-index-files"
    schedule: "*/10 * * * *"
  - fileName: "store-nuvs-files"
    taskName: "store_nuvs_files"
    kubeName: "virtool-task-store-nuvs-files"
    schedule: "*/10 * * * *"
  - fileName: "compress-samples"
    taskName: "compress_samples"
    kubeName: "virtool-task-compress-samples"
    schedule: "*/10 * * * *"
  - fileName: "move-sample-files"
    taskName: "move_sample_files"
    kubeName: "virtool-task-move-sample-files"
    schedule: "*/10 * * * *"
  - fileName: "clean-references"
    taskName: "clean_references"
    kubeName: "virtool-task-clean-references"
    schedule: "*/10 * * * *"
  - fileName: "migrate-files"
    taskName: "migrate_files"
    kubeName: "virtool-task-migrate-files"
    schedule: "*/10 * * * *"
  - fileName: "check-subtractions-fasta-files"
    taskName: "check_subtractions_fasta_files"
    kubeName: "virtool-task-check-subtractions-fasta-files"
    schedule: "*/10 * * * *"
  - fileName: "timeout-jobs"
    taskName: "timeout_jobs"
    kubeName: "virtool-task-timeout-jobs"
    schedule: "*/10 * * * *"
  - fileName: "refresh-reference-releases"
    taskName: "refresh_reference_releases"
    kubeName: "virtool-task-refresh-reference-releases"
    schedule: "*/10 * * * *"
  - fileName: "refresh-hmms"
    taskName: "refresh_hmms"
    kubeName: "virtool-task-refresh-hmms"
    schedule: "*/10 * * * *"
  - fileName: "populate-workflows-field"
    taskName: "populate_workflows_field"
    kubeName: "virtool-task-populate-workflows-field"
    schedule: "*/10 * * * *"
